[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "1.22.17"
  HUGO_VERSION = "0.115.0"

[build]
  command = "yarn build:webpack && hugo -d dist -s site -v"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:webpack && hugo -d dist -s site -v -D -F"

[dev]
  framework = "hugo"
  targetPort = 3000